add_newline = true

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❯](bold green)"

[package]
disabled = true

[cmd_duration]
format = "levou [$duration](bold cyan) "

[directory]
format = "[$path](bold purple)[$read_only]($read_only_style) "

[git_branch]
format = "[$symbol$branch](bold blue) "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )](bold green) '

[rlang]
format = "[$symbol($version )](bold yellow)"
