#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap br &
xrandr --dpi 96 --rate 60 &
nitrogen --restore &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
numlockx on &
xinput --set-prop $(xinput | sed '/USB OPTICAL MOUSE/s/.*id=\([0-9]*\).*/\1/;t;d') 'libinput Accel Speed' -1 &
picom --experimental-backends --config $HOME/.config/picom/picom.conf &
sh $HOME/.config/polybar/launch.sh &
dunst &
xsetroot -cursor_name left_ptr &

# Monitors and workspaces
bspc monitor -d     

# Bspwm configurations
bspc config border_width         4
bspc config window_gap           16
bspc config split_ratio          0.50
# bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

# Bspwm border colors
bspc config focused_border_color     "#EB6C64"
bspc config normal_border_color      "#1d2021"
bspc config urgent_border_color      "#EB6C64"

# Bspwm rules
bspc rule -a mplayer2 state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a firefox desktop='^2'
bspc rule -a Lutris desktop='^3'
bspc rule -a Steam desktop='^3'
bspc rule -a heroic desktop='^3'
bspc rule -a discord desktop='^3'
bspc rule -a Evolution desktop='^4'
bspc rule -a libreoffice desktop='^4'
bspc rule -a libreoffice-writer desktop='^4'
bspc rule -a libreoffice-calc desktop='^4'
bspc rule -a libreoffice-base desktop='^4'
bspc rule -a libreoffice-math desktop='^4'
bspc rule -a libreoffice-draw desktop='^4'
bspc rule -a libreoffice-impress desktop='^4'
